### ISSUE TITLE
Simpler run interface

### ISSUE THREAD

**Issue by conal** [jwiegley/z3cat#1]
Reduce the exposed Z3 mechanism, say as in https://github.com/conal/concat/issues/4#issuecomment-294664367:

``` haskell
runZ3 :: Z3able a => Z3Cat a Bool -> IO (Maybe a)
```
I could take a whack at it.

**Comment by jwiegley** [comment]
There is such a function in `Z3.Category` now, or close to it.

**Comment by conal** [comment]
I just pushed part of the change I had in mind. Now `runZ3` generates its own variables. Next to collect up the results into a regular value instead of a list.

**Comment by conal** [comment]
I think I was working too hard to make *fresh* variable names, instead of letting `mkFreshBoolVar` & friends do it. About to simplify.

**Comment by conal** [comment]
Now the run interface is as I imagined: automatically generated variable *and* reconstruction of values
